export { Deck } from "./components/Deck/Deck"
export { Slide } from "./components/Slide/index"
export type { CardItem } from "./components/Slide/Cards"
export type { ListItem } from "./components/Slide/List"
export { Code } from "./components/Code/Code"
export { Notes } from "./components/Notes/Notes"
export { Image } from "./components/Image/Image"
export { Footnote } from "./components/Footnote/Footnote"
