export { Deck } from "./components/Deck/Deck"
export { Slide } from "./components/Slide/index"
export type { CardItem } from "./components/Slide/Cards"
export { List } from "./components/List/List"
export type { ListItem, ListProps } from "./components/List/List"
export { Code } from "./components/Code/Code"
export { Notes } from "./components/Notes/Notes"
export { Image } from "./components/Image/Image"
export { Video } from "./components/Video/Video"
export { Footnote } from "./components/Footnote/Footnote"
